package com.woniu.pojo;
// Generated 2019-12-18 21:32:32 by Hibernate Tools 5.2.12.Final

import java.util.Date;

/**
 * Attendancerecord generated by hbm2java
 */
public class Attendancerecord implements java.io.Serializable {

	private Integer attendanceRecordId;
	private Attendance attendance;
	private Student student;
	private Date attendanceRecordDate;

	public Attendancerecord() {
	}

	public Attendancerecord(Attendance attendance, Student student) {
		this.attendance = attendance;
		this.student = student;
	}

	public Attendancerecord(Attendance attendance, Student student, Date attendanceRecordDate) {
		this.attendance = attendance;
		this.student = student;
		this.attendanceRecordDate = attendanceRecordDate;
	}

	public Integer getAttendanceRecordId() {
		return this.attendanceRecordId;
	}

	public void setAttendanceRecordId(Integer attendanceRecordId) {
		this.attendanceRecordId = attendanceRecordId;
	}

	public Attendance getAttendance() {
		return this.attendance;
	}

	public void setAttendance(Attendance attendance) {
		this.attendance = attendance;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public Date getAttendanceRecordDate() {
		return this.attendanceRecordDate;
	}

	public void setAttendanceRecordDate(Date attendanceRecordDate) {
		this.attendanceRecordDate = attendanceRecordDate;
	}

}
