package com.woniu.pojo;
// Generated 2019-12-18 21:32:32 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Level generated by hbm2java
 */
public class Level implements java.io.Serializable {

	private int levelId;
	private String levelName;
	private Set clazzs = new HashSet(0);

	public Level() {
	}

	public Level(int levelId) {
		this.levelId = levelId;
	}

	public Level(int levelId, String levelName, Set clazzs) {
		this.levelId = levelId;
		this.levelName = levelName;
		this.clazzs = clazzs;
	}

	public int getLevelId() {
		return this.levelId;
	}

	public void setLevelId(int levelId) {
		this.levelId = levelId;
	}

	public String getLevelName() {
		return this.levelName;
	}

	public void setLevelName(String levelName) {
		this.levelName = levelName;
	}

	public Set getClazzs() {
		return this.clazzs;
	}

	public void setClazzs(Set clazzs) {
		this.clazzs = clazzs;
	}

}
