package com.woniu.pojo;
// Generated 2019-12-18 21:32:32 by Hibernate Tools 5.2.12.Final

/**
 * Scoreresult generated by hbm2java
 */
public class Scoreresult implements java.io.Serializable {

	private Integer scoreResultId;
	private Clazz clazz;
	private Float average;

	public Scoreresult() {
	}

	public Scoreresult(Clazz clazz) {
		this.clazz = clazz;
	}

	public Scoreresult(Clazz clazz, Float average) {
		this.clazz = clazz;
		this.average = average;
	}

	public Integer getScoreResultId() {
		return this.scoreResultId;
	}

	public void setScoreResultId(Integer scoreResultId) {
		this.scoreResultId = scoreResultId;
	}

	public Clazz getClazz() {
		return this.clazz;
	}

	public void setClazz(Clazz clazz) {
		this.clazz = clazz;
	}

	public Float getAverage() {
		return this.average;
	}

	public void setAverage(Float average) {
		this.average = average;
	}

}
