package com.woniu.pojo;
// Generated 2019-12-18 21:32:32 by Hibernate Tools 5.2.12.Final

import java.util.Date;

/**
 * Scorerecord generated by hbm2java
 */
public class Scorerecord implements java.io.Serializable {

	private Integer scoreRecordId;
	private Student student;
	private Float score;
	private Date scoreRecordDate;

	public Scorerecord() {
	}

	public Scorerecord(Student student) {
		this.student = student;
	}

	public Scorerecord(Student student, Float score, Date scoreRecordDate) {
		this.student = student;
		this.score = score;
		this.scoreRecordDate = scoreRecordDate;
	}

	public Integer getScoreRecordId() {
		return this.scoreRecordId;
	}

	public void setScoreRecordId(Integer scoreRecordId) {
		this.scoreRecordId = scoreRecordId;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public Float getScore() {
		return this.score;
	}

	public void setScore(Float score) {
		this.score = score;
	}

	public Date getScoreRecordDate() {
		return this.scoreRecordDate;
	}

	public void setScoreRecordDate(Date scoreRecordDate) {
		this.scoreRecordDate = scoreRecordDate;
	}

}
