package com.woniu.pojo;
// Generated 2019-12-18 21:32:32 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private Integer stuId;
	private Clazz clazz;
	private String stuName;
	private Integer stuIdcard;
	private Integer stuPhone;
	private String stuAddress;
	private Date stuGradTime;
	private Set scorerecords = new HashSet(0);
	private Set attendancerecords = new HashSet(0);

	public Student() {
	}

	public Student(Clazz clazz) {
		this.clazz = clazz;
	}

	public Student(Clazz clazz, String stuName, Integer stuIdcard, Integer stuPhone, String stuAddress,
			Date stuGradTime, Set scorerecords, Set attendancerecords) {
		this.clazz = clazz;
		this.stuName = stuName;
		this.stuIdcard = stuIdcard;
		this.stuPhone = stuPhone;
		this.stuAddress = stuAddress;
		this.stuGradTime = stuGradTime;
		this.scorerecords = scorerecords;
		this.attendancerecords = attendancerecords;
	}

	public Integer getStuId() {
		return this.stuId;
	}

	public void setStuId(Integer stuId) {
		this.stuId = stuId;
	}

	public Clazz getClazz() {
		return this.clazz;
	}

	public void setClazz(Clazz clazz) {
		this.clazz = clazz;
	}

	public String getStuName() {
		return this.stuName;
	}

	public void setStuName(String stuName) {
		this.stuName = stuName;
	}

	public Integer getStuIdcard() {
		return this.stuIdcard;
	}

	public void setStuIdcard(Integer stuIdcard) {
		this.stuIdcard = stuIdcard;
	}

	public Integer getStuPhone() {
		return this.stuPhone;
	}

	public void setStuPhone(Integer stuPhone) {
		this.stuPhone = stuPhone;
	}

	public String getStuAddress() {
		return this.stuAddress;
	}

	public void setStuAddress(String stuAddress) {
		this.stuAddress = stuAddress;
	}

	public Date getStuGradTime() {
		return this.stuGradTime;
	}

	public void setStuGradTime(Date stuGradTime) {
		this.stuGradTime = stuGradTime;
	}

	public Set getScorerecords() {
		return this.scorerecords;
	}

	public void setScorerecords(Set scorerecords) {
		this.scorerecords = scorerecords;
	}

	public Set getAttendancerecords() {
		return this.attendancerecords;
	}

	public void setAttendancerecords(Set attendancerecords) {
		this.attendancerecords = attendancerecords;
	}

}
